#!/usr/bin/env python3
"""
Create a reproducible nnU-Net workspace for this repository.

This script is intentionally cross-platform. It creates the workspace,
a Python virtual environment, nnU-Net runtime directories, and shell helper
files for setting nnU-Net environment variables.

It does NOT install PyTorch automatically because the correct PyTorch build
depends on the operating system, GPU, driver, and CUDA support.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import venv
from pathlib import Path


DATASET_NAME = "Dataset001_AAA"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_workspace() -> Path:
    return repo_root().parent / "AAA-Segmentation-workspace"


def create_virtual_environment(venv_dir: Path) -> None:
    if venv_dir.exists():
        print(f"[OK] Virtual environment already exists: {venv_dir}")
        return

    print(f"[INFO] Creating virtual environment: {venv_dir}")
    builder = venv.EnvBuilder(with_pip=True)
    builder.create(venv_dir)
    print("[OK] Virtual environment created.")


def venv_python(venv_dir: Path) -> Path:
    if os.name == "nt":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def upgrade_pip(venv_dir: Path) -> None:
    python = venv_python(venv_dir)
    print("[INFO] Upgrading pip in the virtual environment...")
    subprocess.check_call([str(python), "-m", "pip", "install", "--upgrade", "pip"])
    print("[OK] pip upgraded.")


def write_shell_helpers(workspace: Path) -> None:
    nnunet_raw = workspace / "nnUNet_raw"
    nnunet_preprocessed = workspace / "nnUNet_preprocessed"
    nnunet_results = workspace / "nnUNet_results"

    ps1 = workspace / "activate_nnunet.ps1"
    sh = workspace / "activate_nnunet.sh"

    # PowerShell single-quoted strings escape apostrophes by doubling them.
    def ps_quote(path: Path) -> str:
        return str(path).replace("'", "''")

    ps1.write_text(
        "\n".join(
            [
                "# Generated by scripts/setup_workspace.py",
                f"$env:nnUNet_raw = '{ps_quote(nnunet_raw)}'",
                f"$env:nnUNet_preprocessed = '{ps_quote(nnunet_preprocessed)}'",
                f"$env:nnUNet_results = '{ps_quote(nnunet_results)}'",
                'Write-Host "nnU-Net paths configured for this PowerShell session."',
                'Write-Host "nnUNet_raw=$env:nnUNet_raw"',
                'Write-Host "nnUNet_preprocessed=$env:nnUNet_preprocessed"',
                'Write-Host "nnUNet_results=$env:nnUNet_results"',
                "",
            ]
        ),
        encoding="utf-8",
    )

    # POSIX shell-safe single quoting.
    def sh_quote(path: Path) -> str:
        return "'" + str(path).replace("'", "'\"'\"'") + "'"

    sh.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "# Generated by scripts/setup_workspace.py",
                f"export nnUNet_raw={sh_quote(nnunet_raw)}",
                f"export nnUNet_preprocessed={sh_quote(nnunet_preprocessed)}",
                f"export nnUNet_results={sh_quote(nnunet_results)}",
                'echo "nnU-Net paths configured for this shell session."',
                'echo "nnUNet_raw=$nnUNet_raw"',
                'echo "nnUNet_preprocessed=$nnUNet_preprocessed"',
                'echo "nnUNet_results=$nnUNet_results"',
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )

    try:
        sh.chmod(sh.stat().st_mode | 0o111)
    except OSError:
        pass

    print(f"[OK] Created: {ps1}")
    print(f"[OK] Created: {sh}")


def write_workspace_manifest(workspace: Path, venv_dir: Path) -> None:
    manifest = {
        "workspace": str(workspace),
        "venv": str(venv_dir),
        "nnUNet_raw": str(workspace / "nnUNet_raw"),
        "nnUNet_preprocessed": str(workspace / "nnUNet_preprocessed"),
        "nnUNet_results": str(workspace / "nnUNet_results"),
        "dataset_source": str(workspace / "data" / "source"),
        "test_ground_truth": str(workspace / "data" / "test_ground_truth"),
    }
    path = workspace / "workspace.json"
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[OK] Created workspace manifest: {path}")


def sync_splits(workspace: Path) -> None:
    source = repo_root() / "configs" / DATASET_NAME / "splits_final.json"
    target_dir = workspace / "nnUNet_preprocessed" / DATASET_NAME
    target = target_dir / "splits_final.json"

    if not source.exists():
        raise FileNotFoundError(f"Repository split file not found: {source}")
    if not target_dir.exists():
        raise FileNotFoundError(
            f"Preprocessed dataset directory does not exist yet: {target_dir}\n"
            "Run nnUNetv2_plan_and_preprocess first, then rerun this script "
            "with --sync-splits."
        )

    shutil.copy2(source, target)
    print(f"[OK] Reproducible cross-validation split copied to: {target}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create the cross-platform workspace used by AAA-Segmentation-nnUNet."
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=default_workspace(),
        help="Workspace directory outside the Git repository. "
             "Default: ../AAA-Segmentation-workspace",
    )
    parser.add_argument(
        "--venv-name",
        default=".venv",
        help="Name of the virtual environment inside the workspace (default: .venv).",
    )
    parser.add_argument(
        "--skip-venv",
        action="store_true",
        help="Create directories and environment helpers without creating a virtual environment.",
    )
    parser.add_argument(
        "--skip-pip-upgrade",
        action="store_true",
        help="Do not upgrade pip after creating the virtual environment.",
    )
    parser.add_argument(
        "--sync-splits",
        action="store_true",
        help="Copy configs/Dataset001_AAA/splits_final.json into the preprocessed dataset. "
             "Use this after nnUNetv2_plan_and_preprocess to reproduce the exact CV split.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    workspace = args.workspace.expanduser().resolve()
    venv_dir = workspace / args.venv_name

    directories = [
        workspace,
        workspace / "nnUNet_raw",
        workspace / "nnUNet_preprocessed",
        workspace / "nnUNet_results",
        workspace / "data",
        workspace / "data" / "source",
        workspace / "data" / "test_ground_truth",
        workspace / "logs",
    ]

    print("=" * 72)
    print("AAA-Segmentation nnU-Net workspace setup")
    print("=" * 72)
    print(f"Repository: {repo_root()}")
    print(f"Workspace:  {workspace}")
    print()

    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)
        print(f"[OK] {directory}")

    if not args.skip_venv:
        created_now = not venv_dir.exists()
        create_virtual_environment(venv_dir)
        if created_now and not args.skip_pip_upgrade:
            upgrade_pip(venv_dir)

    write_shell_helpers(workspace)
    write_workspace_manifest(workspace, venv_dir)

    if args.sync_splits:
        sync_splits(workspace)

    print()
    print("=" * 72)
    print("Next steps")
    print("=" * 72)
    if os.name == "nt":
        print(f"1. Activate venv:  & '{venv_dir / 'Scripts' / 'Activate.ps1'}'")
        print(f"2. Set nnU-Net env: . '{workspace / 'activate_nnunet.ps1'}'")
    else:
        print(f"1. Activate venv:  source '{venv_dir / 'bin' / 'activate'}'")
        print(f"2. Set nnU-Net env: source '{workspace / 'activate_nnunet.sh'}'")
    print("3. Install a compatible PyTorch build for your system.")
    print("4. Install the project dependencies described in README.md.")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
